/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaGUI */

#ifndef _Included_HelloJava
#define _Included_HelloJava
#ifdef __cplusplus
extern "C" {
#endif

	JNIEXPORT jdouble JNICALL Java_HelloJava_calculateSTDDev
	(JNIEnv*, jobject, jintArray);

	JNIEXPORT jdouble JNICALL Java_HelloJava_calculateMean
	(JNIEnv*, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
